name: Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }} for ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            arch: arm64
            target: aarch64-unknown-linux-gnu
          - os: macos-latest
            arch: amd64
            target: x86_64-apple-darwin
          - os: macos-latest
            arch: arm64
            target: aarch64-apple-darwin
          - os: windows-latest
            arch: amd64
            target: x86_64-pc-windows-msvc

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies (Ubuntu)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install pkg-config libssl-dev

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        target: ${{ matrix.target }}

    - name: Build Binary
      run: |
        cd rust
        cargo build --release --manifest-path=crates/mesc_cli/Cargo.toml --target ${{ matrix.target }}

    - name: Publish Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          rust/target/${{ matrix.target }}/release/mesc_cli*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
